version: "3.2"

services:
  web:
    build: 
      context : .
      dockerfile: Dockerfile
    networks:
      - examplenetwork
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres
    networks:
      - examplenetwork
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=admin 

networks:
  examplenetwork: 

volumes:
  postgresql:
  postgresql_data: